### ISSUE TITLE
whoami problem in offline mode

### ISSUE THREAD

**Issue by Pouya47** [packetfu/packetfu#156]
Hi
I have a ruby code like below 
```
$iface = ARGV[0] || "eth0"
$config = PacketFu::Utils.whoami?(:iface => $iface)
ack_packet = PacketFu::TCPPacket.new(:config => $config)
```
 when i'm connect to internet it works fine, but when i'm offline, I get this error
> /var/lib/gems/1.9.1/gems/packetfu-1.1.11/lib/packetfu/utils.rb:145:in `rescue in whoami?': Didn't receive the whoami() packet, can't automatically configure. (SocketError)
> 	from /var/lib/gems/1.9.1/gems/packetfu-1.1.11/lib/packetfu/utils.rb:114:in `whoami?'
> 	from fakestack.rb:10:in `<main>'

What's the problem?
Can I manually create $config variable, without use whoami?

**Comment by claudijd** [comment]
@Pouya47 the whoami functionality within PacketFu uses active traffic to detect it's interface information in the current state.  The code that does this can be found here, if you're curious:

https://github.com/packetfu/packetfu/blob/master/lib/packetfu/utils.rb#L132-L172

It is possible to create PacketFu::Config objects manually, and the code that define config objects can be found in the docs for the config object:

https://github.com/packetfu/packetfu/blob/master/lib/packetfu/config.rb#L21-L24

However, creating a config object manually doesn't necessarily give you the details you would want within that object and currently PacketFu doesn't perform this action for you in an offline state.  With that said, you might be able to manually update the config object by setting the following attributes of the config object that are set in the whois operation if you know them...

https://github.com/packetfu/packetfu/blob/master/lib/packetfu/utils.rb#L152-L162

I am curious about your use case, maybe if you could share more context I can give you a better suggestion on how to proceed with PacketFu to acheive your goal.

**Comment by Pouya47** [comment]
OK, I want to use this ruby file (use packetfu) in **offline mode**.
This script is for testing TCP split hand shake and listen to port 8080 by default in accept TCP connection.

[fakestack.zip](https://github.com/packetfu/packetfu/files/270682/fakestack.zip)
tnx

**Comment by claudijd** [comment]
@Pouya47 I'm going to CC @todb on this since he's also a PacketFu dev and I think he may have coined the term TCP split handshake (or he at least wrote about it here https://nmap.org/misc/split-handshake.pdf) so maybe he's got interest here or would just like to hear someone is working on this.

Back to your problem though, when you say above that you don't have an "Internet connection" can you add more detail about that? Because the purpose of the #whoami? method is to harvest the necessary  interface details (source/dest macs/int) needed to determine what to set on the packets you plan to forge so they are routed properly.  If you're on a air-gapped LAN without a default gateway this could be the reason why you're having issues.  Can you share some more details about your local LAN setup and maybe I can provide more guidance here to help you get on track?

**Comment by claudijd** [comment]
Also, as an aside, since I was also into this type of work at one point. You might also find my BNAT work from 11' of interest => https://github.com/claudijd/bnat

**Comment by Pouya47** [comment]
@claudijd I wan't use this tool in a LAN network that's not connected to internet, and it has a static IP address and don't have default gateway, client connect directly (with a switch) to it.
I wan't to build an Firewall Tester, and it must work in offline mode.
tnx

**Comment by todb-r7** [comment]
@pouya47, since your OS won't have a route in the routing table, you won't be able to automatically derive the MAC for the destination mac. You'll need to populate that yourself and manually decide what interface to use. In other words, you won't be able to use whoami(). You'll have to create packets yourself with TCPPacket.new().

Look at how whoami() constructs the config hash, and fill in those details yourself as a class variable - all you really need is src ip, src mac, dst mac, and interface, if i remember correctly.

**Comment by Pouya47** [comment]
I set default gateway of server the ip address of client and script works!
@todb-r7,  @claudijd , thanks for helping me.
