### ISSUE TITLE
Capture within thread on Ubuntu 14.04

### ISSUE THREAD

**Issue by lucacervasio** [packetfu/packetfu#69]
Hello,
I'm facing a really strange behaviour. I've the following code and it works on Debian 7. The same code on Ubuntu 14.04 doesn't work and doesn't capture packets at all, or randomly I get some packets but not as many as I expect.

``` ruby
#!/usr/bin/env ruby

require 'packetfu'

q = Queue.new

Thread.new {
    cap = ::PacketFu::Capture.new :iface => 'eth2', :promisc => true, :start => true, :filter => 'arp or icmp'
    cap.stream.each do |p|
        q << ::PacketFu::Packet.parse(p)
    end
}


while true
    print q.pop.peek + "\n"
end
```

I tried removing the thread block:

``` ruby
#!/usr/bin/env ruby

require 'packetfu'

cap = ::PacketFu::Capture.new :iface => 'eth0', :promisc => true, :start => true, :filter => 'arp or icmp'
cap.stream.each do |p|
    puts ::PacketFu::Packet.parse(p).peek
end
```

and of course this works perfectly.

I suspect this depends on pcaprub but I'm not sure. Any idea on what's happening ?

I installed on both Debian and Ubuntu the required packets as usual and ended up having the same versions on both systems

```
apt-get install ruby ruby-dev libpcap-dev
gem install pcaprub
gem install packetfu
```

Thanks Luca

**Comment by lucacervasio** [comment]
@claudijd I'm facing the same issue again. I noticed - either on Ubuntu and Debian - that PacketFu randomly can't receive packets when invoked in a ruby script with a high number of threads involved. The same script works fine if I remove the `PacketFu::Capture.new` and I use `PCAPRUB::Pcap.open_live` instead.
I can provide detailed infos if needed. Any ideas of pointer ? 

Thanks
Luca

**Comment by claudijd** [comment]
@lucacervasio how many threads are you talking about?  Also, can you provide an example PoC just so I can replicate the behavior and do some debugging?

I seem to remember something about PacketFu only having a limited buffer (I want to say 30 packets, but I could be way off) before things start sliding off.  I have no tangible basis for this, but I seem to remember something like this happening to me or discussing it with others in the past.

If you're dealing with a high performance situation, you might also consider carving up the layers a bit and see if you can determine if it's libpcap/pcaprub/PacketFu that is dropping packets.  Not that I want to discourage you to not use PacketFu's capture utility, but in the past when I want to "go fast" (like Ricky Bobby) I've cut the capture and parsing components into two parts (a trick I learned from @justfalter).

So, instead of doing this (which happens natively)...

Libpcap => PcapRub => PacketFu

You can try some process layering like this...

FFI::Pcap => PacketFu

It works quite nicely as a drop in replacement for really any capture situation.  You basically do native FFI::PCAP calls and filter packets by either a BPF filter and/or additional details (like maybe data payload contents) and then once you have a valid packet that you want parsed by PacketFu you can parse that packet.  This allows you all the coolio usage of PacketFu while having the control to determine if packets are really dropping off.  You could also just do a packet capture during the process and see if it's being dropped by the kernel.

Let me know if you can produce a native PacketFu PoC or if you explore the FFI::PCAP shimming and what you come up with.  Happy to help and understand exactly what's going on here to ease your pain here.

**Comment by claudijd** [comment]
@lucacervasio I just realized you had code above.  Please let me know if that is sufficient in your current use case.  Thanks!

**Comment by justfalter** [comment]
Chiming in because @claudijd mentioned me. Hi Jon!
The first thing I have to ask is why is your app multi-threaded? You say that you've got lots of threads, and I wonder what those other threads are doing. What are you doing with the packets on the other side of the queue? Ruby MRI can only execute one thread at a time, so any time not spent reading packets from the wire can lead to packet drops. Adding more threads won't help process packets any faster. It's entirely possible that you don't need threading at all, but I can't say for sure unless I knew what your app was doing, exactly. 

If it stops capturing packets entirely, the capture thread might have died. Are you doing a "thread.join(0)" to make sure that your threads are still alive and running? 

Internally, PacketFu::Capture uses PCAPRUB::Pcap.open_live, which you are then accessing via "cap.stream". @lucacervasio, if you are getting a different result when you use PCAPRUB::Pcap.open_live directly, it might be because you are calling open_live with different arguments than PacketFu::Capture. This stuff is unbelievably difficult to debug when you're doing live captures.

**Comment by claudijd** [comment]
@justfalter - thanks for chiming in and sharing some wisdom.

@lucacervasio - looking forward to your response.

**Comment by lucacervasio** [comment]
@justfalter my app has several modules capturing and placing packets on the wire on multiple interfaces, receiving commands and sending logs over websocket, interacting with tty serial interface and so on.

@claudijd I isolated two problems: first one on debian jessie with libpcap0.8-1.6 not being able to receive packets at all both with packetfu and pcaprub. I noticed that reverting on libpcap0.8-1.4 makes everything work.

Second problem happens on ubuntu 15.04 with libpcap0.8-1.6: packetfu randomly looses packets while plain pcaprub open_live works like a charm. I think it depends on different implementation of libpcap and timings, I'm trying to get an excerpt from my code but its huge and difficult to take a simple PoC. Anyway did you never notice such a weird behaviour ? 

Thanks

**Comment by shideneyu** [comment]
Hello @lucacervasio . I think that I encounter your issue at #109 . Which libpcap do you use ? For my part, I use  libpcap0.8:amd 1.5.3-2 and libpcap-dev 1.4.0-2. I can not capture any packet. I'm now quite sur our issues are related.

Can you advice me a packet that I can downgrade ?

And seriously, this is completely messed up.

    ➜  ~  sudo apt-get remove libpcap0.8:amd64
    [sudo] password for shideneyu: 
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      liblinear1 libnet1 sendmail-base sendmail-cf sensible-mda
    Use 'apt-get autoremove' to remove them.
    The following packages will be REMOVED:
      arp-scan dsniff etherape ettercap-common ettercap-graphical libnids1.21
      libpcap-dev libpcap0.8 libpcap0.8-dev mint-meta-core mint-meta-mate
      network-manager-pptp network-manager-pptp-gnome nmap ppp pppconfig pppoe
      pppoeconf pptp-linux reaver tcpdump wireshark wireshark-common
    0 upgraded, 0 newly installed, 23 to remove and 353 not upgraded.
    After this operation, 32.1 MB disk space will be freed.
    Do you want to continue? [Y/n] 

How can I downgrade without having to remove my network_manager first ._. ?

**Comment by lucacervasio** [comment]
I dont' know if they're related or not. My issue is related to a new feature in kernel TPACKET_V3, pcap starting from version 1.5 uses this new feature and breaks things. Then there was a patch in kernel to address this bug. 

So you can either use old version of pcap (1.4 in my tests is ok) or newer version of pcap (>= 1.5) AND kernel >= 3.2.

If you use pcap >= 1.5 AND kernel < 3.2 then you have to tune pcap timeout, but it is not so good to me.

Hope this helps
